version: '3.8'

services: 
  stream:
    # build from ./
    # command = stream
    # set env from .env
    # build: .
    image: sconaway/streamlink-timelapse
    command: stream.py
    env_file: .env
    tty: True
    volumes:
      - "/srv/streamlink-timelapse-big/temp:/temp"
      - "/srv/streamlink-timelapse-big/output:/output"
      - "/etc/localtime:/etc/localtime:ro"
  process:
    # build from ./
    # command = process
    # set env from .env
    # build: .
    image: sconaway/streamlink-timelapse
    command: process.py
    env_file: .env
    tty: True
    volumes:
      - "/srv/streamlink-timelapse-big/temp:/temp"
      - "/srv/streamlink-timelapse-big/output:/output"
      - "/etc/localtime:/etc/localtime:ro"
