version: '3.8'

services: 
  stream:
    # build from ./
    # command = stream
    # set env from .env

    build: .
    command: stream.py
    env_file: .env
    volumes:
      - "/srv/streamlink-timelapse-big/tmp:/tmp"
      - "/srv/streamlink-timelapse-big/out:/out"
  process:
    # build from ./
    # command = process
    # set env from .env

    build: .
    command: process.py
    env_file: .env
    volumes:
      - "/srv/streamlink-timelapse-big/tmp:/tmp"
      - "/srv/streamlink-timelapse-big/out:/out"
